kind: pipeline
type: kubernetes
name: build and push image to harbor

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
steps:
  

  - name: build-and-push
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      dockerfile: Dockerfile
      repo: harbor.pixelslabs.com/testproject/absence
      registry: harbor.pixelslabs.com
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest