kind: pipeline
type: kubernetes
name: build and push image to harbor


steps:
  - name: maven-build
    image: maven:3.8-openjdk-17
    commands:
      - mvn clean package -DskipTests

  
  - name: sonar-analysis
    image: plugins/sonar
    settings:
      sonar_url: "http://sonarservcie.sonarqube.svc.cluster.local:9000"
      sonar_login: 
        from_secret: sonar_token
      sonar_project_key: "absence"
      sonar_project_name: "absence"
      sonar_sources: "src/main/java"
      sonar_exclusions: "**/target/**,**/Dockerfile"
      sonar_java_binaries: "target/classes"
      sonar_java_libraries: "target/dependency/*.jar"
      sonar_java_source: "17" 
      
  - name: build-and-push
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      dockerfile: Dockerfile
      repo: harbor.pixelslabs.com/testproject/absence
      registry: harbor.pixelslabs.com
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest