kind: pipeline
type: kubernetes
name: spring-boot-security-pipeline

trigger:
  event:
    - push
    - pull_request
  branch:
    - master

steps:
  - name: prepare-maven
    image: maven:3.8-openjdk-11
    commands:
      - chmod +x ./mvnw
      
  - name: snyk-code-scan
    image: snyk/snyk:alpine
    environment:
      SNYK_TOKEN:
        from_secret: snyktoken
    commands:
      - export SNYK_API_TOKEN=$${SNYK_TOKEN}
      - snyk code test || true  
      
  - name: build-and-push
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      dockerfile: Dockerfile
      repo: harbor.pixelslabs.com/testproject/absence
      registry: harbor.pixelslabs.com
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest