kind: pipeline
type: docker
name: build and push image to harbor



volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: build and publish
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1  # Enable BuildKit for advanced Docker build features
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      username:
        from_secret: harbor_username 
      password:
        from_secret: harbor_password 
      dockerfile: Dockerfile  # Path to your Dockerfile
      experimental: true  # Enable Docker experimental features (optional)
      repo:  harbor.pixelslabs.com/testproject/absence  # Your Harbor repository
      registry: harbor.pixelslabs.com  # Harbor registry address
      