kind: pipeline
type: kubernetes
name: build and push image to harbor


steps:
  - name: maven-build
    image: maven:3.8-openjdk-17
    commands:
      - mvn clean package -DskipTests
  - name: scan-file
    image: aquasec/trivy:latest
    commands:
      - trivy fs --severity HIGH,CRITICAL .
        --format table
        --output fs-scan-results.txt
      - trivy config --severity HIGH,CRITICAL .
        --format table
        --output dockerfile-scan-results.txt
    artifacts:
      - fs-scan-results.txt
      - dockerfile-scan-results.txt
  - name: install-mc
    image: alpine:latest
    environment:
      MINIO_ACCESS_KEY: minioadmin  # Use your MinIO access key
      MINIO_SECRET_KEY: minioadmin123  # Use your MinIO secret key
    commands:
      - wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /tmp/mc
      - chmod +x /tmp/mc
      - mv /tmp/mc /usr/local/bin/mc
      - mc alias set myminio http://192.168.3.100:30900 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
      - mc cp fs-scan-results.txt myminio/scannerfiles/scan-results/fs-scan-results.txt
      - mc cp dockerfile-scan-results.txt myminio/scannerfiles/scan-results/dockerfile-scan-results.txt

  - name: sonar-analysis
    image: sonarsource/sonar-scanner-cli:4.8
    environment:
      SONAR_HOST_URL: "http://192.168.3.100:30008"
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - sonar-scanner -X -Dsonar.projectKey=absence -Dsonar.projectName=absence -Dsonar.projectVersion=1.0 -Dsonar.sources=src/main/java -Dsonar.host.url=http://192.168.3.100:30008 -Dsonar.login=sqa_1c7f1312c55343bc20292725c84c5ba6fe81663e -Dsonar.java.binaries=target/classes -Dsonar.java.source=17 -Dsonar.sourceEncoding=UTF-8 -Dsonar.exclusions="**/target/**,**/Dockerfile" 
  - name: build-and-push
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      dockerfile: Dockerfile
      repo: harbor.pixelslabs.com/testproject/absence
      registry: harbor.pixelslabs.com
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest