kind: pipeline
type: kubernetes
name: spring-boot-security-pipeline

trigger:
  event:
    - push
    - pull_request
  branch:
    - master

steps:
  - name: snyk-code-scan
    image: snyk/snyk:alpine
    environment:
      SNYK_TOKEN:
        from_secret: snyktoken
    commands:
      - snyk auth $${SNYK_TOKEN}
      - snyk code test || true  # Test for code vulnerabilities
      
  - name: snyk-dependency-scan
    image: snyk/snyk:alpine
    environment:
      SNYK_TOKEN:
        from_secret: snyktoken
    commands:
      - snyk auth $${SNYK_TOKEN}
      - snyk test || true  
      
  - name: snyk-container-scan
    image: snyk/snyk:alpine
    environment:
      SNYK_TOKEN:
        from_secret: snyktoken
    commands:
      - snyk auth $${SNYK_TOKEN}
      - snyk container test harbor.pixelslabs.com/testproject/absence:${DRONE_COMMIT_SHA} --file=Dockerfile --severity-threshold=high || true
      
  - name: build-and-push
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      dockerfile: Dockerfile
      repo: harbor.pixelslabs.com/testproject/absence
      registry: harbor.pixelslabs.com
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest