kind: pipeline
type: kubernetes
name: build and push image to harbor

trigger:
  event:
    - push
    - pull_request
  branch:
    - master

steps:
  - name: build-and-test
    image: maven:3.8.4-openjdk-17
    commands:
      - mvn clean verify
      - mvn jacoco:prepare-agent test jacoco:report
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: sonarqube-analysis
    image: maven:3.8.4-openjdk-17
    environment:
      SONAR_HOST_URL: http://192.168.3.100:30008
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - mvn sonar:sonar 
        -Dsonar.projectKey=absence-ms
        -Dsonar.projectName=absence-ms
        -Dsonar.host.url=$${SONAR_HOST_URL}
        -Dsonar.login=$${SONAR_TOKEN}
        -Dsonar.java.binaries=target/classes
        -Dsonar.sources=src/main/java
        -Dsonar.tests=src/test/java
        -Dsonar.java.source=17
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        -Dsonar.exclusions=**/generated-sources/**,**/model/**,**/entity/**,**/dto/**
        -Dsonar.java.libraries=target/dependency/*.jar
    volumes:
      - name: maven-cache
        path: /root/.m2
    when:
      status:
        - success

  - name: build-and-push
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      dockerfile: Dockerfile
      repo: harbor.pixelslabs.com/testproject/absence
      registry: harbor.pixelslabs.com
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest

volumes:
  - name: maven-cache
    host:
      path: /tmp/maven-cache