
name: Security Scans
on:
  push:
    branches:
      - '*'  # Run on all branches
  pull_request:
    branches:
      - '*'  # Run on pull requests to all branches
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, python, java  # Add languages you want to analyze
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  secret-scanning:
    name: Secret scanning
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
        
      - name: Run secret scanning with TruffleHog
        run: |
          # Install TruffleHog
          curl -sSL https://github.com/trufflesecurity/trufflehog/releases/download/v3.0.3/trufflehog_3.0.3_linux_amd64.tar.gz | tar -xz
          sudo mv trufflehog /usr/local/bin/
          
          # Run TruffleHog with correct syntax
          trufflehog git file://$GITHUB_WORKSPACE --json --branch ${GITHUB_REF#refs/heads/} > trufflehog_report.json || true
          
          # Show the results of the secret scanning
          if [ -f trufflehog_report.json ]; then
            cat trufflehog_report.json
            if grep -q "finding" trufflehog_report.json; then
              echo "::warning ::Potential secrets found in the codebase!"
            fi
          else
            echo "No secrets found or scan failed"
          fi

      - name: Upload TruffleHog report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: trufflehog-report-${{ github.sha }}
          path: trufflehog_report.json
          retention-days: 7

      - name: Check for exposed secrets
        if: always()
        run: |
          if [ -f trufflehog_report.json ] && grep -q "finding" trufflehog_report.json; then
            echo "Potential secrets were found in the codebase. Please review the TruffleHog report."
            exit 1
          fi

  notify:
    name: Notification
    needs: [codeql, secret-scanning]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Check workflow status
        if: always()
        run: |
          if [ "${{ needs.codeql.result }}" == "failure" ] || [ "${{ needs.secret-scanning.result }}" == "failure" ]; then
            echo "::error::Security scan failed! Please check the logs for details."
            exit 1
          fi
