
name: Security Scans

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch, adjust as needed
  pull_request:
    branches:
      - '**'  # Triggers on pull request to any branch, adjust as needed

jobs:
  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CodeQL
        uses: github/codeql-action/setup@v2

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

  secret-scanning:
    name: Secret scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (main repository)
        uses: actions/checkout@v2  # Checkout the main repository

      - name: Install TruffleHog
        run: |
          # Download and install TruffleHog
          curl -sSL https://github.com/trufflesecurity/trufflehog/releases/download/v3.0.3/trufflehog_3.0.3_linux_amd64.tar.gz | tar -xz
          sudo mv trufflehog /usr/local/bin/

      - name: Run TruffleHog for secret scanning
        run: |
          # Ensure we are in the main repository directory
          cd $GITHUB_WORKSPACE  # Change to the main repo's directory

          # Run TruffleHog to scan for secrets in the main repository
          trufflehog --json $GITHUB_WORKSPACE > trufflehog_report.json
          
          # Show the results of the secret scanning
          cat trufflehog_report.json

      - name: Upload TruffleHog results as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: trufflehog_report.json

