name: Security Scans

on:
  push:
    branches:
      - 'security-setup'  # Trigger on secure-branch push, adjust as needed
  pull_request:
    branches:
      - 'security-setup'  # Trigger on pull request to secure-branch

jobs:
  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CodeQL
        uses: github/codeql-action/setup@v2  # Updated to v2

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

  secret-scanning:
    name: Secret scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run secret scanning with TruffleHog
        run: |
          # Install TruffleHog (or GitGuardian for secrets scanning)
          curl -sSL https://github.com/trufflesecurity/trufflehog/releases/download/v3.0.3/trufflehog_3.0.3_linux_amd64.tar.gz | tar -xz
          sudo mv trufflehog /usr/local/bin/

          # Run TruffleHog for secret scanning, using the workspace as the target directory
          trufflehog --json $GITHUB_WORKSPACE > trufflehog_report.json

          # Show the results of the secret scanning
          cat trufflehog_report.json

      # Re-checkout the secure-branch (optional, depending on your use case)
      - name: Re-checkout secure-branch
        uses: actions/checkout@v2
        with:
          ref: secure-branch

      # Upload TruffleHog report (optional, depending on your use case)
      - name: Upload TruffleHog report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: trufflehog_report.json

